title: Chemistry teacher
  name: Genevieve Firmer
  twitter: @Genevieve_Echo
description: >
  Creating an open-access platform for sharing 
  secondary chemistry resources.
  
show_excerpts: false

# Minima date format
minima:
  date_format: "%b %-d, %Y"

# Build settings
theme: minima
