title: Chemistry teacher
author:
  name: GFirmer
description: >
  Creating an open-access platform for sharing 
  secondary chemistry resources.
  
show_excerpts: false

# Minima date format
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: Genevieve_Echo

# Build settings
theme: minima
