title: Chem Ed Doctorate
author: Genevieve Firmer
description: >
  Creating an open-access platform for sharing 
  secondary chemistry resources.
  
google_analytics: UA-NNNNNNNN-N
  
show_excerpts: false

# Minima date format
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: https://twitter.com/Genevieve_Echo 

# Build settings
theme: minima
